apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: django-todo-ap

spec:
    selector:
      app: django-app
    

    ports:
     - protocol: TCP
       port: 80   
       targetPort: 8001
    type: NodePort


